# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('key', models.CharField(default=b'2018-03-08', max_length=50, primary_key=True, serialize=False)),
                ('room_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double', 'double')], default='single', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.RoomType'),
        ),
    ]
